<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetBrowser" Version="4.0.0" />
        <PackageReference Include="DotNetBrowser.Wpf" Version="4.0.0" />
        <PackageReference Include="Microsoft.Playwright" Version="1.51.0" />
    </ItemGroup>

</Project>
