<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net7.0-windows</TargetFramework>
        <UseWpf>true</UseWpf>
        <RootNamespace>Puppeteer</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetBrowser" Version="3.3.5" />
        <PackageReference Include="DotNetBrowser.WPF" Version="3.3.5" />
        <PackageReference Include="protobuf-net" Version="2.4.4" />
        <PackageReference Include="protobuf-net.Reflection" Version="2.3.17" />
        <PackageReference Include="PuppeteerSharp" Version="20.2.2" />
    </ItemGroup>

</Project>
