<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWpf>true</UseWpf>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetBrowser.Wpf" Version="4.3.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\shared\bucket-list.html" Link="bucket-list.html"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
