<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <RootNamespace>ReactExample.Desktop</RootNamespace>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.5" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.5" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.5" />
    <PackageReference Include="DotNetBrowser.AvaloniaUi" Version="3.5.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.32.0" />
    <PackageReference Include="Grpc.Net.Common" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Grpc.AspNetCore.Server" Version="2.71.0" />
    <PackageReference Include="Grpc.AspNetCore.Web" Version="2.71.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0-preview.7.25380.108" />
  </ItemGroup>

  <ItemGroup>
    <!-- Include all .proto files for code generation -->
    <Protobuf Include="../proto/**/*.proto" GrpcServices="Both" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../reactexample/reactexample.esproj">
      <!-- Force MSBuild to consider this project buildable -->
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>

    <!-- Take everything from React build and embed it -->
    <EmbeddedResource Include="../reactexample/dist/**/*" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Rpc\" />
  </ItemGroup>
</Project>
